# Caser Hyperparameter Search Space
learning_rate:
  type: loguniform
  min: 0.00005
  max: 0.01

embedding_size:
  type: choice
  values: [64, 128]

n_v:
  type: choice
  values: [2, 4, 8]

n_h:
  type: choice
  values: [4, 8, 16]

dropout_prob:
  type: uniform
  min: 0.2
  max: 0.5

reg_weight:
  type: loguniform
  min: 0.00001
  max: 0.001

#train_batch_size:
#  type: choice
#  values: [512, 1024, 2048]
