# FDSA Hyperparameter Search Space
learning_rate:
  type: loguniform
  min: 0.00005
  max: 0.01

embedding_size:
  type: choice
  values: [64, 128, 256]

hidden_size:
  type: choice
  values: [64, 128, 256]

n_layers:
  type: choice
  values: [1, 2, 3]

n_heads:
  type: choice
  values: [1, 2, 4]

inner_size:
  type: choice
  values: [128, 256, 512]

hidden_dropout_prob:
  type: uniform
  min: 0.1
  max: 0.5

attn_dropout_prob:
  type: uniform
  min: 0.1
  max: 0.5
