# FOSSIL Hyperparameter Search Space
learning_rate:
  type: loguniform
  min: 0.00005
  max: 0.02

embedding_size:
  type: choice
  values: [64, 128, 256]

order:
  type: choice
  values: [1, 2, 3]

alpha:
  type: uniform
  min: 0.1
  max: 0.9

reg_weight:
  type: loguniform
  min: 0.0000001
  max: 0.01
