# FPMC Hyperparameter Search Space
learning_rate:
  type: loguniform
  min: 0.00005
  max: 0.05

embedding_size:
  type: choice
  values: [64, 128, 256]

reg_weight:
  type: loguniform
  min: 0.0000001
  max: 0.01

train_batch_size:
  type: choice
  values: [2048, 4096, 8192]
