# NARM Hyperparameter Search Space
learning_rate:
  type: loguniform
  min: 0.0001
  max: 0.01

embedding_size:
  type: choice
  values: [128, 256, 512]

hidden_size:
  type: choice
  values: [128, 256, 512]

n_layers:
  type: choice
  values: [1, 2, 3]

dropout_probs:
  type: choice
  values:
    - [0.1, 0.1]
    - [0.3, 0.3]
    - [0.5, 0.3]

train_batch_size:
  type: choice
  values: [1024, 2048, 4096]
