# NextItNet Hyperparameter Search Space
learning_rate:
  type: loguniform
  min: 0.0001
  max: 0.01

embedding_size:
  type: choice
  values: [64, 128, 256]

block_num:
  type: choice
  values: [1, 2, 4]

kernel_size:
  type: choice
  values: [3, 5, 7]

dropout_prob:
  type: uniform
  min: 0.0
  max: 0.5

reg_weight:
  type: loguniform
  min: 0.00001
  max: 0.001

dilations:
  type: choice
  values:
    - [1, 2]
    - [1, 2, 1, 2]
    - [1, 2, 4, 8]
