# SASRec Hyperparameter Search Space
learning_rate:
  type: loguniform
  min: 0.00005
  max: 0.01

hidden_size:
  type: choice
  values: [128, 256, 512]

n_layers:
  type: choice
  values: [2, 3, 4]

n_heads:
  type: choice
  values: [2, 4, 8]

inner_size:
  type: choice
  values: [512, 1024, 2048]

hidden_dropout_prob:
  type: uniform
  min: 0.1
  max: 0.5

attn_dropout_prob:
  type: uniform
  min: 0.1
  max: 0.5
