# STAMP Hyperparameter Search Space
learning_rate:
  type: loguniform
  min: 0.0001
  max: 0.01

embedding_size:
  type: choice
  values: [128, 256, 512]

hidden_size:
  type: choice
  values: [128, 256, 512]

dropout_prob:
  type: uniform
  min: 0.0
  max: 0.5

#train_batch_size:
#  type: choice
#  values: [1024, 2048, 4096]
