# Hyperparameter search space for STAN

k:
  type: quniform
  low: 100
  high: 1000
  q: 50

sample_size:
  type: choice
  values: [1000, 2000, 5000, 10000]

similarity:
  type: choice
  values: [cosine, jaccard]

lambda_spw:
  type: uniform
  low: 1.0
  high: 2.0

lambda_snh:
  type: uniform
  low: 1.0
  high: 10.0

lambda_inh:
  type: uniform
  low: 1.0
  high: 5.0
