# Hyperparameter search space for STAN

k:
  type: quniform
  min: 100
  max: 1000
  q: 50

sample_size:
  type: choice
  values: [1000, 2000, 5000, 10000]

similarity:
  type: choice
  values: [cosine, jaccard]

lambda_spw:
  type: uniform
  min: 1.0
  max: 2.0

lambda_snh:
  type: uniform
  min: 1.0
  max: 10.0

lambda_inh:
  type: uniform
  min: 1.0
  max: 5.0
