type: single
key: ar
data:
  name: realestate_30days
  folder: /home/hygo2025/Development/projects/fermi/session_rec_format/
  prefix: realestate
  type: parquet
  slices: 5
  num_days_train: 5
  num_days_test: 1

results:
  folder: results/pattern_mining/

evaluation: evaluation_last

metrics:
  - class: accuracy.HitRate
    length: [5, 10, 20]
  - class: accuracy.MRR
    length: [5, 10, 20]

algorithms:
  - class: baselines.ar.AssociationRules
    params:
      pruning: 20
    key: ar
