type: single
key: realestate_ar
evaluation: evaluation_last
slices: 1

data:
  name: realestate_march
  folder: /home/hygo2025/Development/projects/fermi/session_rec_format/
  prefix: realestate
  type: parquet

metrics:
- class: accuracy.MRR
  length: [5, 10, 20]
- class: accuracy.HitRate
  length: [5, 10, 20]

algorithms:
- class: baselines.ar.AssociationRules
  params: {}
  key: ar
