---
type: single
key: realestate_markov
evaluation: evaluation_last
data:
  name: realestate_march
  folder: /home/hygo2025/Development/projects/fermi/session_rec_format/
  prefix: realestate
  type: parquet

results:
  folder: results/pattern_mining/

metrics:
- class: accuracy.MRR
  length: [5, 10, 20]
- class: accuracy.HitRate
  length: [5, 10, 20]

algorithms:
- class: baselines.markov.MarkovModel
  params: {}
  key: markov
