# Sequential Rules (SR) Configuration
# Based on session-rec examples

type: single
key: sr
data:
  name: realestate_march
  folder: /home/hygo2025/Development/projects/fermi/session_rec_format/
  prefix: realestate
  type: parquet

results:
  folder: results/pattern_mining/

evaluation: evaluation_last

metrics:
  - class: accuracy.HitRate
    length: [5, 10, 20]
  - class: accuracy.MRR
    length: [5, 10, 20]

algorithms:
  - class: baselines.sr.SequentialRules
    params:
      steps: 10
      weighting: div
    key: sr
