# RECENT - Non-personalized baseline
# Recommends most recently viewed items globally

type: single
key: realestate_recent
evaluation: evaluation_last
slices: 1

data:
  name: realestate_march
  folder: /home/hygo2025/Development/projects/fermi/session_rec_format/
  prefix: realestate
  type: parquet
  slices: 
    - 0
  
results:
  folder: ../results/non_personalized/

metrics:
- class: accuracy.MRR
  length: [5, 10, 20]
- class: accuracy.HitRate  
  length: [5, 10, 20]
- class: coverage.Coverage
  length: [20]
- class: popularity.Popularity
  length: [20]

algorithms:
- class: baselines.sr.SessionRecent
  params: {}
  key: recent
