model: FOSSIL

data_path: recbole_data/

# Training
train_batch_size: 1024
eval_batch_size: 1024

# Model Parameters
embedding_size: 256
order: 3
alpha: 0.5
reg_weight: 0.0001
loss_type: 'CE'

# Gradient Clipping
clip_grad_norm: 
  max_norm: 5.0