model: FOSSIL

# Model Parameters
embedding_size: 128      # Similar ao FPMC, mantemos menor que os Transformers
order: 3                 # Olha para os Ãºltimos 3 itens (Markov Order)
alpha: 0.5               # Peso do termo de similaridade
reg_weight: 0.0001
loss_type: 'CE'

# Gradient Clipping
clip_grad_norm: 
  max_norm: 5.0