model: FPMC

data_path: recbole_data/

# Training
train_batch_size: 1024
eval_batch_size: 1024
neg_sampling:
  uniform: 1
train_neg_sample_args:
  distribution: uniform
  sample_num: 1

# Model Parameters - FPMC (Factorization)
embedding_size: 256
reg_weight: 0.0001

# Gradient Clipping
clip_grad_norm:
  max_norm: 5.0