model: FDSA

embedding_size: 64
hidden_size: 64
n_layers: 2
n_heads: 2
inner_size: 256

MAX_ITEM_LIST_LENGTH: 50

hidden_dropout_prob: 0.2
attn_dropout_prob: 0.2

loss_type: 'CE'
learning_rate: 0.001
