model: GRU4Rec

data_path: recbole_data/

# Training
train_batch_size: 1024
eval_batch_size: 1024

# Model Parameters
embedding_size: 64
hidden_size: 128
num_layers: 2
dropout_prob: 0.3
loss_type: 'CE'

# Gradient Clipping
clip_grad_norm:
  max_norm: 5.0

