model: GRU4Rec

# Model Parameters
embedding_size: 256      # Aumentado de 128 para 256 (Padrão SOTA)
hidden_size: 256         # Deve igualar o embedding_size
num_layers: 1            # 1 camada é suficiente e mais estável para sessões
dropout_prob: 0.3
loss_type: 'CE'

# Gradient Clipping
clip_grad_norm:
  max_norm: 5.0