model: NextItNet

embedding_size: 64
block_num: 2
dilations: [1, 2, 1, 2]
kernel_size: 3

reg_weight: 0.0001
dropout_prob: 0.1

loss_type: 'BPR'

train_neg_sample_args:
  distribution: 'uniform'
  sample_num: 5
  alpha: 1.0
  dynamic: false
  candidate_num: 0
