model: SRGNN

embedding_size: 64
hidden_size: 64
step: 1
train_batch_size: 4096
eval_batch_size: 8192

loss_type: 'BPR'

train_neg_sample_args:
  distribution: 'uniform'
  sample_num: 5
  alpha: 1.0
  dynamic: false
  candidate_num: 0



weight_decay: 0.00001
dropout_prob: 0.1
