model: STAMP

data_path: recbole_data/

# Training - HIGH QUALITY
train_batch_size: 1024
eval_batch_size: 1024

# Model Parameters
embedding_size: 256
hidden_size: 256
dropout_prob: 0.3
loss_type: 'CE'

# Gradient Clipping
clip_grad_norm: 
  max_norm: 5.0