model: TransRec

n_layers: 2
n_heads: 2
embedding_size: 64
inner_size: 256

MAX_ITEM_LIST_LENGTH: 50

hidden_dropout_prob: 0.2
attn_dropout_prob: 0.2
dropout_prob: 0.2
weight_decay: 0.0

loss_type: 'CE'
learning_rate: 0.001
hidden_act: 'gelu'
layer_norm_eps: 0.000000000001
initializer_range: 0.02
