model: TransRec

n_layers: 2
n_heads: 2
embedding_size: 64
inner_size: 256

MAX_ITEM_LIST_LENGTH: 50

hidden_dropout_prob: 0.2
attn_dropout_prob: 0.2
dropout_prob: 0.2
weight_decay: 0.0

learning_rate: 0.001
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
train_batch_size: 4096
eval_batch_size: 8192

# TransRec SEMPRE precisa de negative sampling (pair-wise optimization)
train_neg_sample_args:
  distribution: 'uniform'
  sample_num: 1
