type: single
key: sknn
data:
  name: realestate_30days
  folder: /home/hygo2025/Development/projects/fermi/session_rec_format/
  prefix: realestate
  type: parquet
  slices: 5
  num_days_train: 5
  num_days_test: 1

results:
  folder: results/knn/

evaluation: evaluation_last

metrics:
  - class: accuracy.HitRate
    length: [5, 10, 20]
  - class: accuracy.MRR
    length: [5, 10, 20]

algorithms:
  - class: models.knn.sknn.ContextKNN
    params:
      k: 500
      sample_size: 1000
      sampling: recent
      similarity: cosine
      remind: false
      pop_boost: 0
      extend: false
      normalize: true
    key: sknn
