type: single
key: vsknn
data:
  name: realestate_30days
  folder: /home/hygo2025/Development/projects/fermi/session_rec_format/
  prefix: realestate
  type: parquet
  slices: 5
  num_days_train: 5
  num_days_test: 1

results:
  folder: results/knn/

evaluation: evaluation_last

metrics:
  - class: accuracy.HitRate
    length: [5, 10, 20]
  - class: accuracy.MRR
    length: [5, 10, 20]

algorithms:
  - class: knn.vsknn.VMContextKNN
    params:
      k: 500
      sample_size: 1000
      sampling: recent
      similarity: cosine
      weighting: div
      dwelling_time: false
      extend: false
      weighting_score: div
      weighting_time: false
      normalize: true
    key: vsknn
