type: single
key: vstan
data:
  name: realestate_30days
  folder: /home/hygo2025/Development/projects/fermi/session_rec_format/
  prefix: realestate
  type: parquet
  slices: 5
  num_days_train: 5
  num_days_test: 1

results:
  folder: results/knn/

evaluation: evaluation_last

metrics:
  - class: accuracy.HitRate
    length: [5, 10, 20]
  - class: accuracy.MRR
    length: [5, 10, 20]

algorithms:
  - class: knn.vstan.VSKNN_STAN
    params:
      k: 500
      sample_size: 5000
      sampling: recent
      remind: true
      extend: false
      similarity: cosine
      lambda_spw: 1.02
      lambda_snh: 5
      lambda_inh: 2.05
      lambda_ipw: 1.02
      lambda_idf: 5
    key: vstan
